### ISSUE TITLE
jars missing dm me the jars

### ISSUE THREAD

**Issue by jredfox** [Digiex/MCLauncher.NET#6]
hi I work with omni-archive and we collect minecraft jars. I noticed that your launcher was done as soon as the new launcher came up. The new launcher has alot of jars but it's missing alot as well. Can you provide all the jars you can find and email them at jredfox@hotmail.com or add me on discord directly. jredfox#0992 .

**Comment by jessenic** [comment]
I managed to find all the jars we had in the launcher and emailed them to you. They had survived a few server moves, good thing they weren't deleted!

**Comment by jredfox** [comment]
ok thanks dude. i will check the hashes with omni's in case any are missing. omni archive also has more non modified jars the the real launcher does

**Comment by jredfox** [comment]
I noticed idev was missing? I thought you added before the 2013 new launcher was it modified? I could be mistaking it with minecraft version changer which I checked out in 2013 as well.

**Comment by jredfox** [comment]
ok no new jars were found. However if you have any indev jars that I could have sworn your launcher use to have email me again.
